#logging:
#  level: debug
server:
  port: 8761
security:
  basic:
    enabled: false  #开启基于HTTP basic的认证
  user:
    name: admin    #配置登陆名
    password: ${cipher}123456   #配置登陆密码
---
spring:
  profiles: cks
  application:
    name: eureka

eureka:
  instance:
#    prefer-ip-address: true
    hostname: 127.0.0.1 #加这个就必须改hosts文件的主机名
  client:
#单节点要加这个，不让注册中心自己注册自己
    registerWithEureka: false
    fetchRegistry: false #这个参数上注册缓存
    serviceUrl:
#      defaultZone: http://127.0.0.1:8761/eureka/
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

#---
#spring:
#  profiles: cks1
#  application:
#    name: eureka
#server:
#  port: 8762
#eureka:
#  instance:
##    hostname: cks1
#    prefer-ip-address: true
#  client:
##单节点要加这个，不让注册中心自己注册自己
#    registerWithEureka: false
#    fetchRegistry: false #这个参数上注册缓存
#    serviceUrl:
#      defaultZone: http://192.168.16.78:8761/eureka/
